language: generic
sudo: required
services:
  - docker

before_install:
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  - docker build -t jagadishmadhu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true -t jagadishmadhu/react-test npm test

after_success:
  - docker build -t jagadishmadhu/multi-client ./client
  - docker build -t jagadishmadhu/multi-nginx ./nginx
  - docker build -t jagadishmadhu/multi-server ./server
  - docker build -t jagadishmadhu/multi-worker ./worker
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  # Take those images and push them to docker hub.
  - docker push jagadishmadhu/multi-client
  - docker push jagadishmadhu/multi-nginx
  - docker push jagadishmadhu/multi-server
  - docker push jagadishmadhu/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: multi-docker
  env: MultiDocker-env-1
  bucket_name: elasticbeanstalk-ap-south-1-336242118500
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

